---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backuper-rabbitmq
  namespace: ${OPENSHIFT_WORKSPACE}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pods-reader
  namespace: ${OPENSHIFT_WORKSPACE}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward", "pods/attach"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-reader
  namespace: ${OPENSHIFT_WORKSPACE}
subjects:
- kind: ServiceAccount
  name: backuper-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-reader
