---
kind: Template
apiVersion: v1
metadata:
  name: rabbitmq-backup-daemon
  annotations:
    openshift.io/display-name: rabbitmq backup daemon
labels:
  template: rabbitmq-backup-daemon-template
parameters:
- name: BACKUP_STORAGE_SIZE
  description: storage size for backup pv
  required: false
  value: 1Gi
- name: BACKUP_STORAGE_CLASS
  description: storage class for backup pv
  required: false
- name: BACKUP_STORAGE_PV
  description: backup storage pv
objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: "${BACKUP_STORAGE_CLASS}"
      name: rabbitmq-backup-storage
      labels:
        app: rabbitmq-backup-daemon
        microservice: rabbitmq-backup-daemon
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "${BACKUP_STORAGE_SIZE}"
      storageClassName: "${BACKUP_STORAGE_CLASS}"
      volumeName: "${BACKUP_STORAGE_PV}"