{{- if and .Values.tests.runTests .Values.tests.atpReport.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-integration-tests-atp-storage-secret
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
type: Opaque
stringData:
  atp-storage-username: {{ (include "tests.atpStorageUsername" .) | quote }}
  atp-storage-password: {{ (include "tests.atpStoragePassword" .) | quote }}
{{- end }}
