DEPLOY_W_HELM: "true"
operatorImage: artifactorycn.netcracker.com:17152/netcracker/qubership-rabbitmq-operator:main
global:
  cloudIntegrationEnabled: false
  podReadinessTimeout: 540
allowEvents: false
name: rabbitmq-service
loglevel: DEBUG
rabbitmqPrometheusMonitoring: true
operator:
  restartScheduler:
    dockerImage: artifactorycn.netcracker.com:17152/netcracker/qubership-docker-kubectl:main
  resources:
    requests:
      cpu: 120m
      memory: 120Mi
    limits:
      cpu: 120m
      memory: 120Mi
rabbitmq:
  dockerImage: artifactorycn.netcracker.com:17152/netcracker/qubership-rabbitmq-image:main
  dockerImage3: artifactorycn.netcracker.com:17152/netcracker/qubership-rabbitmq-image-3:main
  securityContext:
    runAsUser: 5000
    fsGroup: 5000
  replicas: 3
  hostpath_configuration: false
  validate_state: true
  clean_rabbitmq_pvs: false
  auto_reboot: true
  setDefaultQueueTypeClassic: true
  nodePortService:
    install: true
  ingress:
    enabled: true
    host: fibu0125-rabbitmq-service.ci-master.openshift.sdntest.netcracker.com
  custom_params:
    rabbitmq_vm_memory_high_watermark: 80%
    rabbitmq_default_user: admin
    rabbitmq_default_password: admin
  customConfigProperties:
    - raft.adaptive_failure_detector.poll_interval = 2500
    - raft.wal_max_size_bytes = 32000000
  customAdvancedProperties:
    - "{kernel, [{net_ticktime, 120}]}"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
    storageclass: local-path
  storage: 5Gi
  enabledPlugins:
    - rabbitmq_prometheus
  perQueueMetrics: true
backupDaemon:
  image: artifactorycn.netcracker.com:17152/netcracker/qubership-rabbitmq-backup-daemon:main
  enabled: true
  backupSchedule: "*/5 * * * *"
  evictionPolicy: 1/10min,10min/delete
  storage: 1Gi
  storageClass: csi-cinder-sc-delete
  securityContext:
    runAsUser: 5000
    fsGroup: 5000
  s3:
    enabled: true
    url: https://infra-platform.s3.netcracker.com
    bucket: rabbitmq-qa
    keyId: plat-rw
    keySecret: Netcracker123
    sslCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR3VENDQXFtZ0F3SUJBZ0lRVDdENkhSemFzSjlKTFJ4Y2lLTGlWakFOQmdrcWhraUc5dzBCQVFzRkFEQlUKTVJNd0VRWUtDWkltaVpQeUxHUUJHUllEWTI5dE1Sb3dHQVlLQ1pJbWlaUHlMR1FCR1JZS2JtVjBZM0poWTJ0bApjakVoTUI4R0ExVUVBeE1ZVG1WMFEzSmhZMnRsY2lCVVpXTm9ibTlzYjJkNUlFTkJNQjRYRFRFMk1EVXhPREE0Ck1qZzFNbG9YRFRNeE1EVXhPREE0TXpnMU1sb3dWREVUTUJFR0NnbVNKb21UOGl4a0FSa1dBMk52YlRFYU1CZ0cKQ2dtU0pvbVQ4aXhrQVJrV0NtNWxkR055WVdOclpYSXhJVEFmQmdOVkJBTVRHRTVsZEVOeVlXTnJaWElnVkdWagphRzV2Ykc5bmVTQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKM0dyblNGCmhNVWw4MmtxZFhKM3RmdTMvbnRrK3FVTVE3RmJoSmxudmJYcGJ0T1NPcHd3U1JSclBKNEs5V2NLdmMrK08vdGkKVUo4eFZnbHVkOG1MbGYxcUxxQVdNRGhFbnptMThrZ0tWdFFvc2pmaTNQbkV5MmtHR2RZZjRtN0p3bEt6V0lJZwpGMUVBWmNNSGc5V1VpQ21pSm13OFV3djVaRi9qUzcvVFFQUFd2QUpWbFBMcnI5TE5lRVl3azAwSlQvVnkrYnlaCkIvN1V4TEh1UXBSSTdmYVJaYldHbmhhUlpFeU1GSUMvMnQ1U0UrWUxiYTdyQktwbFg0MytPdUdhK0F1T2EzZkkKemx0NVZiUWhWVWY1VUkxM3RGUi9KMFlaSW0vZm5YdUdsMU13YWJSQnRpMURsSGwrNkQ2ZFhSa2VLOEpJdEhocgp1ZS9wQ0pDaUR4anNuejBDQXdFQUFhT0JqakNCaXpBVEJna3JCZ0VFQVlJM0ZBSUVCaDRFQUVNQVFUQUxCZ05WCkhROEVCQU1DQVlZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXJYNllnQkhJNU43K1ZOYkMKN0hOOCtMYnlSQ1l3RWdZSkt3WUJCQUdDTnhVQkJBVUNBd0lBQWpBakJna3JCZ0VFQVlJM0ZRSUVGZ1FVdzlQMgpQdGJZNkdTQzVYVTBrb3dQdlc1VlV4c3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQmlYbVR4Y0RUNnZTMXJQCkQwMU52SjFsby9hbXVJYmdDd2hVenVaSjg4TTJGVlo1c0NkUng4TGJ6WHVlL0VBMEhMZTB5R0tQOE9yQTlTMEEKQkV6YTFtR2dBeFBpQldMUERVMFFpVzNCay9Cb29iMUhVVFdnUng2RHQzbjBRM3FVRzhrMWp0cUpKZ0JOdHdoSwpkbGVkbWtuWExsdE5zb3daeFoyYkdWejdXQ0pKZHREcGgrMitDaHhkNVlEVTQrQmlVQ0thcmdVanAyQm1vQS8wCkwzaWQyQlVuLzFGc1dGOUdqYWwycTFsWThrcjZUdFFkenV6bUlwaTVsNGtCS1oyOENVcitiYldmMmVvc204eXgKVmU0OTdOM0hObSsvTWdTU1JOT2tnRTUzY1ZVb2VUK0xGT3NNNjkvQlNhamsxUXZBUXZoSC80UXdZdzVTWVlqZQpSVmpoVko0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
tests:
  dockerImage: artifactorycn.netcracker.com:17152/netcracker/qubership-rabbitmq-integration-tests:main
  runTests: true
  runTestsOnly: false
  runAsUser: 5000
  timeout: 1200
  waitTestResultOnJob: true
  rabbitmq_port: 15672
  amqp_port: 5672
  tags: backup
disasterRecovery:
  image: artifactorycn.netcracker.com:17152/netcracker/qubership-disaster-recovery-daemon:main
telegraf:
  dockerImage: artifactorycn.netcracker.com:17152/netcracker/qubership-rabbitmq-monitoring:main
statusProvisioner:
  dockerImage: artifactorycn.netcracker.com:17152/netcracker/qubership-deployment-status-provisioner:main
ESCAPE_SEQUENCE: "true"
