{
 "title": "RabbitMQ",
 "description": "Metrics for RabbitMQ service",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cloud", "label": "Cloud", "query": "influxdb" },
   {
    "name": "namespace",
    "label": "Openshift project",
    "query": "SHOW TAG VALUES FROM \"cpu/usage\" WITH KEY = \"namespace_name\""
   },
   {
    "name": "vhost",
    "label": "Vhost",
    "query": "SHOW TAG VALUES FROM \"rabbitmq_queue\" WITH KEY = \"vhost\" where namespace = '$namespace'"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "SHOW TAG VALUES FROM \"cpu/usage\" WITH KEY = \"pod_name\"  WHERE \"namespace_name\" = '$namespace' and \"pod_name\" =~ /^rmqlocal/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster state",
   "type": "singlestat",
   "description": "UP - All nodes are running.\nDOWN - All nodes are down.\nDEGRADED - Some nodes are running.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "query": "SELECT last(status) FROM \"rabbitmq_cluster_state\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "expected_number_of_nodes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Telegraf Status",
   "type": "singlestat",
   "description": "UP - telegraf pod is in a running state.\nDOWN - telegraf pod is down.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "telegraf",
     "query": "SELECT min(\"status\") as min_status FROM \"telegraf\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory alarm",
   "type": "singlestat",
   "description": "When memory use goes above the configured limit, then RabbitMQ will stop \nreading from client network sockets in order to prevent crashes.",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "query": "SELECT max(\"mem_alarm\") FROM \"rabbitmq_node\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "mem_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk alarm",
   "type": "singlestat",
   "description": "When disk space drops below the configured limit, then RabbitMQ will stop \nreading from client network sockets in order to prevent crashes.",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "query": "SELECT max(\"disk_free_alarm\") FROM \"rabbitmq_node\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "disk_free_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of ready messages",
   "type": "singlestat",
   "description": "The count of the messages available to the consumer.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "query": "SELECT max(\"messages\") FROM \"rabbitmq_overview\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rate of Unroutable Messages",
   "type": "singlestat",
   "description": "The count of the messages not routed to a queue.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT last(\"return_unroutable_rate\") FROM \"rabbitmq_overview\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_unroutable_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "singlestat",
   "description": "Number of client connections to RabbitMQ",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "query": "SELECT last(\"connections\") FROM \"rabbitmq_overview\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "connections" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Publish In/Out",
     "type": "graph",
     "description": "Number of messages that \nhave entered the exchange and the number of messages that have left.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Queue" }
     ],
     "targets": [
      {
       "alias": "In: Vhost: $tag_vhost Queue $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_exchange",
       "query": "SELECT max(\"messages_publish_in\") FROM \"rabbitmq_exchange\" WHERE \"namespace\" = '$namespace' AND \"vhost\" =~ /^$vhost$/ AND $timeFilter GROUP BY time($__interval), queue, vhost fill(0)",
       "select": [
        [
         { "params": [ "messages_publish_in" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      },
      {
       "alias": "Out: Vhost: $tag_vhost Queue $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_exchange",
       "query": "SELECT max(\"messages_publish_out\") FROM \"rabbitmq_exchange\" WHERE \"namespace\" = '$namespace' AND \"vhost\" =~ /^$vhost$/ AND $timeFilter GROUP BY time($__interval), queue, vhost fill(0)",
       "select": [
        [
         { "params": [ "messages_publish_out" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Messages Publish In/Out Rate",
     "type": "graph",
     "description": "Number of messages\n per second that have entered the exchange and the number of messages that have left.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "Messages" }
     ],
     "targets": [
      {
       "alias": "In: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_exchange",
       "query": "SELECT max(\"messages_publish_in_rate\") FROM \"rabbitmq_exchange\" WHERE \"namespace\" = '$namespace' AND \"vhost\" =~ /^$vhost$/ AND $timeFilter GROUP BY time($__interval), queue, vhost fill(0)",
       "select": [
        [
         { "params": [ "messages_publish_in_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      },
      {
       "alias": "Out: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_exchange",
       "query": "SELECT max(\"messages_publish_out_rate\") FROM \"rabbitmq_exchange\" WHERE \"namespace\" = '$namespace' AND \"vhost\" =~ /^$vhost$/ AND $timeFilter GROUP BY time($__interval), queue, vhost fill(0)",
       "select": [
        [
         { "params": [ "messages_publish_out_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    },
    {
     "title": "HealthChecks (0 = DOWN, 1 = OK)",
     "type": "graph",
     "description": "Healthchecks checks that the rabbit \napplication is running, that channels and queues can be listed successfully, \nand that no alarms are in effect: 0 - OK, 1 - Failed",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" }
       ],
       "measurement": "rabbitmq_node",
       "query": "SELECT last(\"health_check_status\") FROM \"rabbitmq_node\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval), \"node\"",
       "select": [
        [
         { "params": [ "health_check_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Smoketests",
     "type": "graph",
     "description": "Declares a test queue, then publishes and consumes a message.\nShows what a time was spent on the smoketest.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "test duration",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" }
       ],
       "measurement": "rabbitmq_smoketest",
       "query": "SELECT last(\"duration\") FROM \"rabbitmq_smoketest\" WHERE \"namespace\" = '$namespace' AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status: $pod",
     "type": "singlestat",
     "description": "UP - Specific RabbitMQ pod has a running state.\nDOWN - Specific RabbitMQ pod is down.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
     "repeat": "pod",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select last(\"value\") / last(\"value\") as \"value\" from \"uptime\" WHERE \"namespace_name\"='$namespace' AND \"pod_name\"='$pod' AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Status: $pod",
     "type": "singlestat",
     "description": "UP - Specific RabbitMQ pod has a running state.\nDOWN - Specific RabbitMQ pod is down.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select last(\"value\") / last(\"value\") as \"value\" from \"uptime\" WHERE \"namespace_name\"='$namespace' AND \"pod_name\"='$pod' AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Status: $pod",
     "type": "singlestat",
     "description": "UP - Specific RabbitMQ pod has a running state.\nDOWN - Specific RabbitMQ pod is down.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select last(\"value\") / last(\"value\") as \"value\" from \"uptime\" WHERE \"namespace_name\"='$namespace' AND \"pod_name\"='$pod' AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Uptime: $pod",
     "type": "singlestat",
     "description": "Pod uptime",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "repeat": "pod",
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "uptime",
       "query": "SELECT last(\"value\") FROM \"uptime\" WHERE \"namespace_name\" = '$namespace' AND \"pod_name\" =~ /^$pod$/ AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$pod$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime: $pod",
     "type": "singlestat",
     "description": "Pod uptime",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "uptime",
       "query": "SELECT last(\"value\") FROM \"uptime\" WHERE \"namespace_name\" = '$namespace' AND \"pod_name\" =~ /^$pod$/ AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$pod$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime: $pod",
     "type": "singlestat",
     "description": "Pod uptime",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "uptime",
       "query": "SELECT last(\"value\") FROM \"uptime\" WHERE \"namespace_name\" = '$namespace' AND \"pod_name\" =~ /^$pod$/ AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$pod$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "description": "CPU usage in millicores by RabbitMQ pods",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Millicores" }
     ],
     "targets": [
      {
       "alias": "Usage: $tag_pod_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "pod_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu/usage_rate",
       "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/ AND \"pod_name\" =~ /^$service/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$pod$/" }
       ]
      },
      {
       "alias": "Limit: $tag_pod_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "pod_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu/limit",
       "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/ AND \"pod_name\" =~ /^$service/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^$pod$/" }
       ]
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "description": "Network traffic by RabbitMQ pods",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "Bps", "label": "Millicores" }
     ],
     "targets": [
      {
       "alias": "rx: $tag_pod_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "pod_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "network/rx_rate",
       "query": "SELECT sum(\"value\") FROM \"system_metrics\".\"network/rx_rate\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /^$namespace$/ AND \"pod_name\" =~ /^rmqlocal/) AND $timeFilter GROUP BY time($interval), \"pod_name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^rmqlocal/" }
       ]
      },
      {
       "alias": "tx: $tag_pod_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "pod_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "network/tx_rate",
       "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/ AND \"pod_name\" =~ /^$service/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^rmqlocal/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "Memory usage by RabbitMQ pods",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Millicores" }
     ],
     "targets": [
      {
       "alias": "Usage: $tag_pod_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "pod_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "memory/usage",
       "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/ AND \"pod_name\" =~ /^$service/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^rmqlocal/" }
       ]
      },
      {
       "alias": "Limit: $tag_pod_name",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "pod_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "memory/limit",
       "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /^$project$/ AND \"pod_name\" =~ /^$service/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/^rmqlocal/" }
       ]
      }
     ]
    },
    {
     "title": "Disk space",
     "type": "graph",
     "description": "Disk space consumed by RabbitMQ pods",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Free $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "disk_free" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Limit $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "disk_free_limit" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "graph",
     "description": "File descriptors consumed by RabbitMQ pods",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Used $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "fd_used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Total $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "fd_total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sockets",
     "type": "graph",
     "description": "Sockets consumed by RabbitMQ pods",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Used $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "sockets_used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Total $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "sockets_total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deliver Rate",
     "type": "graph",
     "description": "Delivered messages per second to the client",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT mean(\"messages_deliver_rate\") FROM \"rabbitmq_queue\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($interval), \"queue\", \"vhost\" fill(0)",
       "select": [
        [
         { "params": [ "messages_deliver_rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Redeliver Rate",
     "type": "graph",
     "description": "Redelivered messages per second to the client",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT mean(\"messages_deliver_rate\") FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($interval), \"queue\", \"vhost\" fill(null)",
       "select": [
        [
         { "params": [ "messages_redeliver_rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Publish Rate",
     "type": "graph",
     "description": "Messages published to an exchange per second",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT mean(\"messages_deliver_rate\") FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($interval), \"queue\", \"vhost\" fill(null)",
       "select": [
        [
         { "params": [ "messages_publish_rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Ack Rate",
     "type": "graph",
     "description": "Count of messages a queue has delivered with receiving \nacknowledgment from a consumer.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT mean(\"messages_deliver_rate\") FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($interval), \"queue\", \"vhost\" fill(null)",
       "select": [
        [
         { "params": [ "messages_ack_rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "Memory - All memory was consumed by a queue. Memory RAM - Sum in bytes of messages stored in memory. Memory Persistence - Sum in bytes of messages written to disk.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "alias": "Memory: Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT last(\"memory\") FROM \"rabbitmq_queue\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"vhost\" =~ /^$vhost$/) AND $timeFilter GROUP BY time($inter), \"queue\", \"vhost\" fill(0)",
       "select": [
        [
         { "params": [ "memory" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      },
      {
       "alias": "Message Persist Bytes: Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT last(\"message_bytes_ram\") FROM \"rabbitmq_queue\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"vhost\" =~ /^$vhost$/) AND $timeFilter GROUP BY time($inter), \"queue\", \"vhost\" fill(0)",
       "select": [
        [
         { "params": [ "message_bytes_ram" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      },
      {
       "alias": "Message Ram Bytes: Vhost: $tag_vhost Queue: $tag_queue",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "vhost" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT last(\"message_bytes_ram\") FROM \"rabbitmq_queue\" WHERE (\"namespace\" =~ /^$namespace$/ AND \"vhost\" =~ /^$vhost$/) AND $timeFilter GROUP BY time($inter), \"queue\", \"vhost\" fill(0)",
       "select": [
        [
         { "params": [ "message_bytes_ram" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" },
        { "condition": "AND", "key": "vhost", "operator": "=~", "value": "/^$vhost$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Mnesia",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Disk Mnesia transactions",
     "type": "graph",
     "description": "Number of Memory Mnesia transactions",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "query": "SELECT mean(\"mnesia_disk_tx_count\") FROM \"rabbitmq_node\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter GROUP BY time($interval), \"node\"",
       "select": [
        [
         { "params": [ "mnesia_disk_tx_count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Memory Mnesia transactions",
     "type": "graph",
     "description": "Number of Memory Mnesia transactions per second",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "mnesia_ram_tx_count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Rate of Disk Mnesia transactions",
     "type": "graph",
     "description": "Rate of Memory Mnesia transactions",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "mnesia_disk_tx_count_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Rate of Memory Mnesia transactions",
     "type": "graph",
     "description": "Rate of Memory Mnesia transactions per second",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "mnesia_ram_tx_count_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "IO Read/Write average times",
     "type": "graph",
     "description": "IO Read/Write average times",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Read: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_read_avg_time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Write: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_write_avg_time" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "IO Read/Write average times  rate",
     "type": "graph",
     "description": "IO Read/Write average times per second",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Read: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_read_avg_time_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Write: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_write_avg_time_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "IO Read/Write bytes",
     "type": "graph",
     "description": "IO Read/Write bytes",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Read: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Write: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "IO Read/Write bytes rate",
     "type": "graph",
     "description": "IO Read/Write bytes per second",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Read: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_read_bytes_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "alias": "Write: $tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "io_write_bytes_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Reclaimed",
     "type": "graph",
     "description": "Rate of Reclaimed Bytes",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "gc_bytes_reclaimed" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Rate of Reclaimed Bytes",
     "type": "graph",
     "description": "Rate of Reclaimed Bytes per second",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "gc_bytes_reclaimed_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of Garbage Collection",
     "type": "graph",
     "description": "Number of Garbage Collections",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "gc_num" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    },
    {
     "title": "Rate of Garbage Collection Number",
     "type": "graph",
     "description": "Number of Garbage Collections per second",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_node",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "node" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_node",
       "select": [
        [
         { "params": [ "gc_num_rate" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}