{{ if not .Values.externalRabbitmq.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-operator-rollout
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: rabbitmq-operator-rollout
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
