{{- if .Values.backupDaemon.enabled }}
{{- $s3Data := fromYaml (include "backupDaemon.s3Aliases" .) }}
{{- if $s3Data.items }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-backup-daemon-s3-aliases
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/technology: python
    app.kubernetes.io/name: rabbitmq-backup-daemon
    name: rabbitmq-backup-daemon
    app.kubernetes.io/instance: rabbitmq-backup-daemon{{ .Values.DELIMITER }}{{ .Release.Namespace }}
    app: rabbitmq-backup-daemon
type: Opaque
stringData:
  s3_aliases.json: |
{{ include "backupDaemon.s3AliasesJson" . | indent 4 }}
{{- end }}
{{- end }}
