{{- if and (eq (include "rabbitmq.enableDisasterRecovery" .) "true") (and .Values.disasterRecovery.httpAuth.enabled (not .Values.disasterRecovery.httpAuth.restrictedEnvironment)) }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
  name: token-review-crb-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: rabbitmq-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
{{- end }}