{{ if and .Values.telegraf (not .Values.externalRabbitmq.enabled) }}
apiVersion: v1
data:
  influxdb-debug: {{ default "false" .Values.telegraf.influxdbDebug | b64enc }}
  metric-collection-interval: {{ default "30s" .Values.telegraf.metricCollectionInterval | b64enc }}
  influxdb-url: {{ default "no.host.url" .Values.telegraf.influxdbUrl | b64enc }}
  influxdb-database: {{ default "rabbit_database" .Values.telegraf.influxdbDatabase | b64enc }}
  influxdb-user: {{ default "admin" .Values.telegraf.influxdbUser | b64enc }}
  influxdb-password: {{ default "admin" .Values.telegraf.influxdbPassword | b64enc }}
kind: Secret
metadata:
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
  name: rabbitmq-monitoring
type: Opaque
{{ end }}