{{ if not .Values.externalRabbitmq.enabled }}
apiVersion: v1
data:
  password: {{ include "rabbitmq.adminPassword" . | b64enc }}
  rmqcookie: {{ default "secretcookie" .Values.rabbitmq.custom_params.secretcookie | b64enc }}
  user: {{ include "rabbitmq.adminUsername" . | b64enc }}
kind: Secret
metadata:
  labels:
    deploy.{{ .Values.operator.apiGroup }}/change-credentials: "true"
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
  name: rabbitmq-default-secret
type: Opaque
{{ end }}