{{ if and .Values.externalRabbitmq.enabled .Values.telegraf.install}}
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-monitoring-service-external
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
    name: rabbit-monitoring-external
    app.kubernetes.io/name: rabbit-monitoring-external
spec:
  ports:
    - name: rabbitmq-monitoring-statsd
      protocol: TCP
      port: 8125
      targetPort: 8125
    - name: rabbitmq-monitoring-tcp
      protocol: TCP
      port: 8094
      targetPort: 8094
    - name: rabbitmq-monitoring-udp
      protocol: UDP
      port: 8092
      targetPort: 8092
    - name: prometheus-cli
      protocol: TCP
      port: 8096
      targetPort: 8096
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    name: rabbit-monitoring-external
{{ end }}