{{ if and (eq (include "monitoring.enabled" .) "true") (not .Values.externalRabbitmq.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-service-monitor
  labels:
    {{- include "rabbitmq.coreLabels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  endpoints:
  - interval: 30s
    port: 15692-tcp
    path: /metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: rmqlocal
{{ end }}
