#!/bin/bash
set -e
rabbitmqctl change_password "$1" "$2"
set +e
ENCODED_USER=$(printf %s "$1" | base64)
ENCODED_PASSWORD=$(printf %s "$2" | base64)
if [ "${RABBITMQ_ENABLE_IPV6}" == "True" ];
then
  KUBERNETES_SERVICE_HOST_MODIFIED="[$KUBERNETES_SERVICE_HOST]"
else
  KUBERNETES_SERVICE_HOST_MODIFIED=$KUBERNETES_SERVICE_HOST
fi
curl -k -X PATCH -d @- -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H 'Accept: application/json' -H 'Content-Type: application/json-patch+json' https://"$KUBERNETES_SERVICE_HOST_MODIFIED":"$KUBERNETES_SERVICE_PORT_HTTPS"/api/v1/namespaces/"$MY_POD_NAMESPACE"/secrets/rabbitmq-default-secret <<EOF
   [
      { "op": "replace", "path": "/data/user", "value": "$ENCODED_USER" },
      { "op": "replace", "path": "/data/password", "value": "$ENCODED_PASSWORD" }
   ]
EOF
