---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: ${OPENSHIFT_WORKSPACE}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: ${OPENSHIFT_WORKSPACE}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-patcher-and-reader
  namespace: ${OPENSHIFT_WORKSPACE}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", patch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: ${OPENSHIFT_WORKSPACE}
subjects:
- kind: ServiceAccount
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-patcher-and-reader
  namespace: ${OPENSHIFT_WORKSPACE}
subjects:
- kind: ServiceAccount
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-patcher-and-reader