{{- if and .Values.statusProvisioner.enabled .Values.externalRabbitmq.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
  name: rabbitmq-status-provisioner
rules:
  - apiGroups:
      - {{ .Values.operator.apiGroup }}
    resources:
      - "*"
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs/status
    verbs:
      - get
      - patch
{{- end }}
