{{- if and .Values.statusProvisioner.enabled .Values.externalRabbitmq.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
  name: rabbitmq-status-provisioner
{{- end }}
