{{- if and .Values.statusProvisioner.enabled .Values.externalRabbitmq.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "rabbitmq.defaultLabels" . | nindent 4 }}
  name: rabbitmq-status-provisioner-cleanup
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
{{- end }}
