name: Build Artifacts
permissions:
  contents: read
  packages: write
  actions: read
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'CODE-OF-CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'CODE-OF-CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'SECURITY.md'

concurrency:
  # On main/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-rabbitmq-integration-tests
            file: operator/operator-robot-image/Dockerfile
            context: operator/operator-robot-image
          - name: qubership-rabbitmq-operator
            file: operator/Dockerfile
            context: operator
          - name: qubership-rabbitmq-transfer
            file: docker-transfer/Dockerfile
            context: ""
          - name: qubership-rabbitmq-backup-daemon
            file: rabbitmq-backup-daemon/Dockerfile
            context: rabbitmq-backup-daemon
          - name: qubership-rabbitmq-performance-tests-image
            file: performance-tests-image/Dockerfile
            context: performance-tests-image
          - name: qubership-rabbitmq-monitoring
            file: telegraf/Dockerfile
            context: telegraf
          - name: qubership-rabbitmq-image
            file: rabbitmq-docker/4.0/Dockerfile
            context: rabbitmq-docker
          - name: qubership-rabbitmq-image-3
            file: rabbitmq-docker/3.13/Dockerfile
            context: rabbitmq-docker
    runs-on: ubuntu-latest
    name: ${{ matrix.component.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.component.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ steps.meta.outputs.tags }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          # See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#fetching-metadata-about-a-pull-request
          push: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
