name: Run Nightly Rabbitmq Pipeline

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  Nightly-Rabbitmq-Pipeline:
    uses: Netcracker/qubership-test-pipelines/.github/workflows/rabbitmq.yaml@c46738acd2481dcea8b4cd0bee83e3f4f4539f2c #v1.11.0
    with:
      service_branch: 'main'
      pipeline_branch: 'c46738acd2481dcea8b4cd0bee83e3f4f4539f2c' #this value must match the value after '@' in 'uses'
      scope: 'nightly'
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
